fix: Skip if paths not defined
The TailwindJit builder was causing a problem in the console while running `reload!`.

Specifically:
```
undefined method `length' for nil:NilClass (NoMethodError)
```

Checking the existence of `paths` solved the issue.